version: '3'
services:
  tp_ecommerce:
    build: .
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql_ecommerce:3306/TP_Ecommerce?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      DB_USERNAME: root
      DB_PASSWORD: 123
      DB_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      DB_JPA_HIBERNATE_DDL_AUTO: update
    restart: always
    depends_on:
      mysql_ecommerce:
        condition: service_healthy
  mysql_ecommerce:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: TP_Ecommerce
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10